version: "3.7"

services:
  app:
    build:
      context: .
      
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 && flake8"

    environment:
      - DB_HOST=db
      - DB_NAME=sigcd
      - DB_USER=sigcd
      - DB_PASS=superusersecret

    # depends_on:
    #   - db
    #   - redis

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_DB=sigcd
      - POSTGRES_USER=sigcd
      - POSTGRES_PASSWORD=superusersecret

    ports:
      - "5432:5432"

  # redis:
  #   image: redis:5-alpine
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_REPLICATION_MODE=master

  #   ports:
  #     - "6379:6379"

  # celery:
  #   build: 
  #     context: .
  #   command: >
  #     sh -c "celery -A app worker -l info"
  #   volumes:
  #     - ./app:/app

  #   depends_on:
  #     - db
  #     - redis
  
  # celery-beat:
  #   build: 
  #     context: .
  #   command: >
  #     sh -c  "celery -A app beat -l info"
  #   #  sh -c  "celery -A app beat -l info --scheduler django_celery_beat.scheduler:DatabaseScheduler"
  #   volumes:
  #     - ./app:/app

  #   depends_on:
  #     - db
  #     - redis

