version: "3"

services:
  app:
    build:
      context: .
      
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 && flake8"

    environment:
      - DB_HOST=db
      - DB_NAME=sigcd
      - DB_USER=sigcd
      - DB_PASS=superusersecret

    depends_on:
      - db
    #  - redis

  db:
    image: postgres:10-alpine
    #restart: always
    environment:
      - POSTGRES_DB=sigcd
      - POSTGRES_USER=sigcd
      - POSTGRES_PASSWORD=superusersecret

    ports:
      - "5432:5432"
