# Generated by Django 3.1.1 on 2020-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitente',
            name='tipo',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Empresa', 'Empresa')], max_length=10),
        ),
    ]
